# Конфиг для проверки
# Logger config
logger:
  level: "DEBUG"
# HTTP server config
httpServer:
  host: 0.0.0.0
  port: 8080
  readTimeout: "5s"
# Database config
database:
  master: # master
    uri: postgres://otus:password@localhost:5432/backend
    connect:
      maxConns: 80
      maxConnLifetime: "1h"
      maxConnIdleTime: "10m"
  # replicas: # replicas, may be absent or uri may be empty
  #   uri: "postgres://otus:password@localhost:5433/backend,postgres://otus:password@localhost:5434/backend" # uri list
  #   connect:
  #     maxConns: 80
  #     maxConnLifetime: "1h"
  #     maxConnIdleTime: "10m"
# Timezone
timezone: "Europe/Moscow"
# Auth config
auth:
  # openssl ecparam -name prime256v1 -genkey -noout -out ecprivatekey.pem
  PrivateKey: |-
    -----BEGIN EC PRIVATE KEY-----
    MHcCAQEEIN2dALnjdcZaIZg4QuA6Dw+kxiSW502kJfmBN3priIhPoAoGCCqGSM49
    AwEHoUQDQgAE4pPyvrB9ghqkT1Llk0A42lixkugFd/TBdOp6wf69O9Nndnp4+HcR
    s9SlG/8hjB2Hz42v4p3haKWv3uS1C6ahCQ==
    -----END EC PRIVATE KEY-----
# Queue config
queue:
  uri: amqp://rmuser:rmpassword@localhost:5672/
  exchangeName: "backend-events"
  exchangeType: "direct" # direct|fanout|topic|x-custom
  postFeedCacheQueue:
    queueName: "post-feed-cache-queue" # общая очередь для равномерного распределения нагрузки
    routingKey: "post-feed-cache"
    consumerTag: "backend-consumer-%v" # разный тег для каждого экземпляра
  postFeedUserQueue:
    queueName: "post-feed-%v-queue-%v" # очередь для конкретного пользователя и конкретного экземпляра
    routingKey: "post-feed-%v" # роутинг по конкретному пользователю
    consumerTag: "backend-consumer-%v-%v" # разный тег для каждого экземпляра и пользователя
# Saga queue config
sagaQueue:
  uri: amqp://rmuser:rmpassword@localhost:5672/
  exchangeName: "backend-saga-events"
  exchangeType: "direct" # direct|fanout|topic|x-custom
  userCreatedQueue:
    routingKey: "user-created"
  verifierStatusQueue:
    queueName: "verifier-status-queue"
    routingKey: "verifier-status"
    consumerTag: "backend-saga-social-consumer-%v"
# Post feed config
postFeed:
  maxSize: 1000 # максимальное количество постов в ленте
# Dialogue config
dialogue:
  baseUri: http://localhost:8081
# Caches config (use different db)
caches:
  subscribers:
    uri: redis://localhost:6379/0?protocol=3&db=0
    ttl: 60m
  postFeed:
    uri: redis://localhost:6379/1?protocol=3&db=1
    ttl: 60m