package: internalhttp
output: server.gen.go
generate:
  gorilla-server: true
  strict-server: true
  embedded-spec: true
output-options:
  skip-prune: true
additional-imports:
  - alias: .
    package: github.com/olga-larina/otus-highload/dialog/internal/model