{
 "title": "Backend RED Metrics",
 "description": "HTTP RED metrics visualization",
 "tags": [
  "red",
  "http"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "job", "label": "Job", "query": { "query": "label_values(job)" } },
   { "name": "instance", "label": "Instance", "query": { "query": "label_values(instance)" } }
  ]
 },
 "panels": [
  {
   "title": "Slowest HTTP routes (P95)",
   "type": "table",
   "description": "the slowest HTTP routes sorted by response time percentile",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sort_desc(topk by(path, job) (5,  max by (path, job) (histogram_quantile(0.95,  (sum by(path, job, le) (rate({__name__=\"highload_http_server_response_time_bucket\",instance=~\"$instance\",job=~\"$job\"}[$__rate_interval])))))))",
     "legendFormat": "{{job}} - {{http_route}}"
    }
   ]
  },
  {
   "title": "Slowest HTTP routes (P95)",
   "type": "table",
   "description": "the slowest HTTP routes sorted by response time percentile",
   "gridPos": { "h": 5, "w": 10, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sort_desc(topk by(path, job) (5,  max by (path, job) (histogram_quantile(0.95,  (sum by(path, job, le) (rate({__name__=\"highload_http_server_response_time_bucket\",instance=~\"$instance\",job=~\"$job\"}[$__rate_interval])))))))",
     "legendFormat": "{{job}} - {{http_route}}"
    }
   ]
  },
  {
   "title": "Duration total",
   "type": "timeseries",
   "description": "average and top percentiles for HTTP traffic total",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(job, le) (rate({__name__=\"highload_http_server_response_time_bucket\",instance=~\"$instance\",job=~\"$job\"}[$__rate_interval])))",
     "legendFormat": "p99 {{job}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate({__name__=\"highload_http_server_response_time_bucket\",instance=~\"$instance\",job=~\"$job\"}[$__rate_interval])) by (job, le))",
     "legendFormat": "p95 {{job}}"
    },
    {
     "expr": "sum(rate({__name__=\"highload_http_server_response_time_sum\",instance=~\"$instance\",job=~\"$job\"} [$__rate_interval])) by (job) / sum(rate({__name__=\"highload_http_server_response_time_count\",instance=~\"$instance\",job=~\"$job\"} [$__rate_interval])) by (job)",
     "legendFormat": "Avg {{job}}"
    }
   ]
  },
  {
   "title": "Request rate total",
   "type": "timeseries",
   "description": "number of requests per second, faceted by its HTTP return code",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate({__name__=\"highload_http_server_requests_total\",instance=~\"$instance\",job=~\"$job\"} [$__rate_interval])) by (status,job)",
     "legendFormat": "{{job}}: status={{status}}"
    }
   ]
  },
  {
   "title": "Error rate total",
   "type": "timeseries",
   "description": "percentage of 4xx|5xx HTTP responses over the total of the requests",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (job, status) (rate({__name__=\"highload_http_server_errors_total\",instance=~\"$instance\",job=~\"$job\"}[$__rate_interval])) / ignoring(status) group_left sum by (job) (rate({__name__=\"highload_http_server_requests_total\",instance=~\"$instance\",job=~\"$job\"}[$__rate_interval])) ",
     "legendFormat": "{{job}}: status={{status}}"
    }
   ]
  },
  {
   "title": "Duration by path",
   "type": "timeseries",
   "description": "average and top percentiles for HTTP traffic total",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(job, path, le) (rate({__name__=\"highload_http_server_response_time_bucket\",instance=~\"$instance\",job=~\"$job\"}[$__rate_interval])))",
     "legendFormat": "p99 {{job}}: {{path}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate({__name__=\"highload_http_server_response_time_bucket\",instance=~\"$instance\",job=~\"$job\"}[$__rate_interval])) by (job, path,le))",
     "legendFormat": "p95 {{job}}: {{path}}"
    },
    {
     "expr": "sum(rate({__name__=\"highload_http_server_response_time_sum\",instance=~\"$instance\",job=~\"$job\"} [$__rate_interval])) by (job, path) / sum(rate({__name__=\"highload_http_server_response_time_count\",instance=~\"$instance\",job=~\"$job\"} [$__rate_interval])) by (job, path)",
     "legendFormat": "Avg {{job}}: {{path}}"
    }
   ]
  },
  {
   "title": "Request rate by path",
   "type": "timeseries",
   "description": "number of requests per second, faceted by its HTTP return code",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate({__name__=\"highload_http_server_requests_total\",instance=~\"$instance\",job=~\"$job\"} [$__rate_interval])) by (job, status, path)",
     "legendFormat": "{{job}}: {{path}}, status={{status}}"
    }
   ]
  },
  {
   "title": "Error rate total by path",
   "type": "timeseries",
   "description": "percentage of 4xx|5xx HTTP responses over the total of the requests",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (job, path, status) (rate({__name__=\"highload_http_server_errors_total\",instance=~\"$instance\",job=~\"$job\"}[$__rate_interval])) / ignoring(status) group_left sum by (job, path) (rate({__name__=\"highload_http_server_requests_total\",instance=~\"$instance\",job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "{{job}}: {{path}}, status={{status}}"
    }
   ]
  }
 ]
}