scrape_configs:
- job_name: 'backend-social-server'
  scrape_interval: 5s
  static_configs:
  - targets:
    - "backend-social-server:8080"
- job_name: 'backend-dialog-server'
  scrape_interval: 5s
  static_configs:
  - targets:
    - "backend-dialog-server:8080"
- job_name: 'cadvisor'
  scrape_interval: 5s
  static_configs:
  - targets:
    - "cadvisor:8080"
- job_name: 'node-exporter'
  scrape_interval: 5s
  static_configs:
  - targets:
    - "node-exporter:9100"