package: clienthttp
output: client.gen.go
generate:
  client: true
output-options:
  skip-prune: true
additional-imports:
  - alias: .
    package: github.com/olga-larina/otus-highload/social/internal/model