# Logger config
logger:
  level: "INFO"
# HTTP server config
httpServer:
  host: ${HTTP_SERVER_HOST}
  port: ${HTTP_SERVER_PORT}
  readTimeout: "5s"
# Database config
database:
  master: # master
    uri: ${DB_MASTER_URI}
    connect:
      maxConns: 80
      maxConnLifetime: "1h"
      maxConnIdleTime: "10m"
  replicas: # replicas, may be absent or uri may be empty
    uri: ${DB_REPLICAS_URI}
    connect:
      maxConns: 80
      maxConnLifetime: "1h"
      maxConnIdleTime: "10m"
# Timezone
timezone: "Europe/Moscow"
# Auth config
auth:
  PrivateKey: ${AUTH_PRIVATE_KEY}