# Logger config
logger:
  level: "DEBUG"
# HTTP server config
httpServer:
  host: ${HTTP_SERVER_HOST}
  port: ${HTTP_SERVER_PORT}
  readTimeout: "5s"
# Database config
database:
  master: # master
    uri: ${DB_MASTER_URI}
    connect:
      maxConns: 80
      maxConnLifetime: "1h"
      maxConnIdleTime: "10m"
  replicas: # replicas, may be absent or uri may be empty
    uri: ${DB_REPLICAS_URI}
    connect:
      maxConns: 80
      maxConnLifetime: "1h"
      maxConnIdleTime: "10m"
# Timezone
timezone: "Europe/Moscow"
# Auth config
auth:
  PrivateKey: ${AUTH_PRIVATE_KEY}
# Queue config
queue:
  uri: ${QUEUE_URI}
  exchangeName: "backend-events"
  exchangeType: "direct" # direct|fanout|topic|x-custom
  queueName: "post-feed-queue"
  routingKey: "post-feed"
  consumerTag: "backends-consumer"
# Post feed config
postFeed:
  maxSize: 1000 # максимальное количество постов в ленте
# Caches config (use different db)
caches:
  subscribers:
    uri: ${SUBSCRIBERS_CACHE_URI}
    ttl: 60m
  postFeed:
    uri: ${POST_FEED_CACHE_URI}
    ttl: 60m