# Logger config
logger:
  level: "INFO"
# HTTP server config
httpServer:
  host: ${HTTP_SERVER_HOST}
  port: ${HTTP_SERVER_PORT}
  readTimeout: "5s"
# Database config
database:
  driver: "pgx"
  uri: ${DB_URI}
# Timezone
timezone: "Europe/Moscow"
# Auth config
auth:
  PrivateKey: ${AUTH_PRIVATE_KEY}